# Generated by Django 5.1.4 on 2024-12-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0004_rename_full_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
