# Generated by Django 5.1.4 on 2024-12-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0006_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='digitaldevice',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='professionalinfo',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='healthfitness',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='securitypreference',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='smarthomedevice',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='recentupdate',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='healthfitness',
            name='health_goals',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_type',
        ),
        migrations.AddField(
            model_name='healthfitness',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='healthfitness',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfitness',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthfitness',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='linked_asset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=50)),
                ('languages_spoken', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('favorite_item', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_preferences', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('first_event_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrations', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=50)),
                ('licence_plate', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('date_purchased', models.DateField()),
                ('odometer_at_purchase', models.IntegerField()),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField()),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('sq_ft', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution', models.CharField(max_length=100)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('period', models.CharField(max_length=10)),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_percent', models.FloatField()),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField()),
                ('apr', models.FloatField()),
                ('upfront_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='PersonalAI.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TravelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('membership_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('rewards_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_memberships', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('supervisor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='PersonalAI.personalprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='DigitalDevice',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
        migrations.DeleteModel(
            name='ProfessionalInfo',
        ),
        migrations.AddField(
            model_name='insurance',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='PersonalAI.personalprofile'),
        ),
        migrations.AddField(
            model_name='healthfitness',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_fitness', to='PersonalAI.personalprofile'),
        ),
        migrations.DeleteModel(
            name='SecurityPreference',
        ),
        migrations.DeleteModel(
            name='SmartHomeDevice',
        ),
        migrations.DeleteModel(
            name='RecentUpdate',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
