# Generated by Django 5.1.4 on 2024-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0007_remove_contact_profile_remove_dailytask_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
