# Generated by Django 5.1.4 on 2024-12-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0009_remove_personalprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='user',
        ),
    ]
