# Generated by Django 5.1.4 on 2024-12-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0011_personalprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='healthfitness',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='travelmembership',
            name='rewards_balance',
        ),
    ]
