# Generated by Django 5.1.4 on 2024-12-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0015_remove_car_profile_remove_celebration_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='languages_spoken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
