# Generated by Django 5.1.4 on 2024-12-27 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0018_alter_car_user_alter_celebration_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalProfile',
            new_name='Profile',
        ),
    ]
