# Generated by Django 5.1.4 on 2024-12-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalAI', '0022_remove_celebration_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
